### ISSUE TITLE
GitHub renders hard tabs in this repository as 8 spaces

### ISSUE THREAD

**Issue by jplatte** [communityvi/communityvi#344]
I don't know whether this is intentional. If you set the tab width to a different value in `.editorconfig`, GitHub will adjust its rendering.

Additionally, for Rust code I would strongly recommend to keep the default 4-space indentation, but I get that you intentionally set rustfmt to use hard tabs and so you probably won't take my advice.

**Comment by FSMaxB** [comment]
Thanks for the tip. I will do that.

As for tabs vs. spaces: @winfr34k and me prefer the semantic of 1 tab being 1 unit of indentation over whatever the supposed benefits of spaces for indentation are, but let's not get into that age old discussion here :wink:.

**Comment by FSMaxB** [comment]
Btw: You can set your preferred tab size on GitHub in the "Appearance" settings:
![grafik](https://user-images.githubusercontent.com/4294942/141194306-4935ec6e-3e0b-440d-99ea-6b07f3901b30.png)

**Comment by jplatte** [comment]
That has to be new 😯

Thanks!
